#!/bin/bash
paths=(
  "/lib/x86_64-linux-gnu/libudev.so.1" # Ubuntu, Xubuntu, Mint
  "/usr/lib64/libudev.so.1" # SUSE, Fedora
  "/usr/lib/libudev.so.1" # Arch, Fedora 32bit
  "/lib/i386-linux-gnu/libudev.so.1" # Ubuntu 32bit
)
for i in "${paths[@]}"
do
  res=$(echo $i | sed "s/so.1/so.0/g")
  if [ -f $i ]
  then
    ln -sf "$i" "$res"
    break
  fi
done
